use super::decoders;
use crate::tlv::{TLVDecodeError, TLVValue};
pub struct DataElement {
    pub tag: u16,
    pub name: &'static str,
    pub short_name: Option<&'static str>,
    pub decoder: &'static (dyn Fn(&[u8]) -> Result<TLVValue, TLVDecodeError> + Sync),
}

pub static ELEMENTS: &'static [DataElement] = &[
    DataElement {
        tag: 0x0042,
        name: "Issuer Identification Number (IIN)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x004f,
        name: "Application Dedicated File (ADF) Name",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0050,
        name: "Application Label",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0057,
        name: "Track 2 Equivalent Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x005a,
        name: "Application Primary Account Number (PAN)",
        short_name: Some("PAN"),
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0061,
        name: "Application Template",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x006f,
        name: "File Control Information (FCI) Template",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0070,
        name: "READ RECORD Response Message Template",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0071,
        name: "Issuer Script Template 1",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0072,
        name: "Issuer Script Template 2",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0073,
        name: "Directory Discretionary Template",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0077,
        name: "Response Message Template Format 2",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0080,
        name: "Response Message Template Format 1",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0081,
        name: "Amount, Authorised (Binary)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0082,
        name: "Application Interchange Profile",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0083,
        name: "Command Template",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0084,
        name: "Dedicated File (DF) Name",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0086,
        name: "Issuer Script Command",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0087,
        name: "Application Priority Indicator",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0088,
        name: "Short File Identifier (SFI)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0089,
        name: "Authorisation Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x008a,
        name: "Authorisation Response Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x008c,
        name: "Card Risk Management Data Object List 1 (CDOL1)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x008d,
        name: "Card Risk Management Data Object List 2 (CDOL2)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x008e,
        name: "Cardholder Verification Method (CVM) List",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x008f,
        name: "Certification Authority Public Key Index",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0090,
        name: "Issuer Public Key Certificate",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0091,
        name: "Issuer Authentication Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0092,
        name: "Issuer Public Key Remainder",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0093,
        name: "Signed Static Application Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0094,
        name: "Application File Locator (AFL)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0095,
        name: "Terminal Verification Results",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0097,
        name: "Transaction Certificate Data Object List (TDOL)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x0098,
        name: "Transaction Certificate (TC) Hash Value",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x009a,
        name: "Transaction Date",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x009b,
        name: "Transaction Status Information",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x009c,
        name: "Transaction Type",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x009d,
        name: "Directory Definition File (DDF) Name",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x00a5,
        name: "File Control Information (FCI) Proprietary Template",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f20,
        name: "Cardholder Name",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f24,
        name: "Application Expiration Date",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f25,
        name: "Application Effective Date",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f28,
        name: "Issuer Country Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f2a,
        name: "Transaction Currency Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f2d,
        name: "Language Preference",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f30,
        name: "Service Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f36,
        name: "Transaction Currency Exponent",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f50,
        name: "Issuer URL",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f53,
        name: "International Bank Account Number (IBAN)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f54,
        name: "Bank Identifier Code (BIC)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f55,
        name: "Issuer Country Code (alpha2 format)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f56,
        name: "Issuer Country Code (alpha3 format)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x5f57,
        name: "Account Type",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f01,
        name: "Acquirer Identifier",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f02,
        name: "Amount, Authorised (Numeric)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f03,
        name: "Amount, Other (Numeric)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f04,
        name: "Amount, Other (Binary)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f05,
        name: "Application Discretionary Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f06,
        name: "Application Identifier (AID) - terminal",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f07,
        name: "Application Usage Control",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f08,
        name: "Application Version Number",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f09,
        name: "Application Version Number",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f0b,
        name: "Cardholder Name Extended",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f0d,
        name: "Issuer Action Code - Default",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f0e,
        name: "Issuer Action Code - Denial",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f0f,
        name: "Issuer Action Code - Online",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f10,
        name: "Issuer Application Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f11,
        name: "Issuer Code Table Index",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f12,
        name: "Application Preferred Name",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f14,
        name: "Lower Consecutive Offline Limit",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f15,
        name: "Merchant Category Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f16,
        name: "Merchant Identifier",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f17,
        name: "Personal Identification Number (PIN) Try Counter",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f18,
        name: "Issuer Script Identifier",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f1a,
        name: "Terminal Country Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f1b,
        name: "Terminal Floor Limit",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f1c,
        name: "Terminal Identification",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f1d,
        name: "Terminal Risk Management Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f1e,
        name: "Interface Device (IFD) Serial Number",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f1f,
        name: "Track 1 Discretionary Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f20,
        name: "Track 2 Discretionary Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f21,
        name: "Transaction Time",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f22,
        name: "Certification Authority Public Key Index",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f23,
        name: "Upper Consecutive Offline Limit",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f26,
        name: "Application Cryptogram",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f27,
        name: "Cryptogram Information Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f2d,
        name: "ICC PIN Encipherment Public Key Certificate",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f2e,
        name: "ICC PIN Encipherment Public Key Exponent",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f2f,
        name: "ICC PIN Encipherment Public Key Remainder",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f32,
        name: "Issuer Public Key Exponent",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f33,
        name: "Terminal Capabilities",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f34,
        name: "Cardholder Verification Method (CVM) Results",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f35,
        name: "Terminal Type",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f36,
        name: "Application Transaction Counter (ATC)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f37,
        name: "Unpredictable Number",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f38,
        name: "Processing Options Data Object List (PDOL)",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f39,
        name: "Point-of-Service (POS) Entry Mode",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f3a,
        name: "Amount, Reference Currency",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f3b,
        name: "Application Reference Currency",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f3c,
        name: "Transaction Reference Currency Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f3d,
        name: "Transaction Reference Currency Exponent",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f40,
        name: "Additional Terminal Capabilities",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f41,
        name: "Transaction Sequence Counter",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f42,
        name: "Application Currency Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f43,
        name: "Application Reference Currency Exponent",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f44,
        name: "Application Currency Exponent",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f45,
        name: "Data Authentication Code",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f46,
        name: "ICC Public Key Certificate",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f47,
        name: "ICC Public Key Exponent",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f48,
        name: "ICC Public Key Remainder",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f4a,
        name: "Static Data Authentication Tag List",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f4b,
        name: "Signed Dynamic Application Data",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f4c,
        name: "ICC Dynamic Number",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f4d,
        name: "Log Entry",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f4e,
        name: "Merchant Name and Location",
        short_name: None,
        decoder: &decoders::binary,
    },
    DataElement {
        tag: 0x9f4f,
        name: "Log Format",
        short_name: None,
        decoder: &decoders::binary,
    },
];
